//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Company.ReportLanguage
{
	internal static partial class Constants
	{
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string DesignerFileExtension = "report";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductName = @"ReportLanguage";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string CompanyName = @"Company";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductVersion = "1.0.0.0";

		// Menu definitions
		public static readonly global::System.ComponentModel.Design.CommandID ReportLanguageDiagramMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(ReportLanguageCommandSetId), 0x10000);
		public static readonly global::System.ComponentModel.Design.CommandID ReportLanguageExplorerMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(ReportLanguageCommandSetId), 0x10001);

		// Command definitions
		public static readonly global::System.ComponentModel.Design.CommandID ViewReportLanguageExplorerCommand = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(ReportLanguageCommandSetId), 0x0001);
	
		// Package identifier
		public const string ReportLanguagePackageId = "68d426da-855a-444b-ab61-2d36420528df";
		
		// Editor factory identifier
		public const string ReportLanguageEditorFactoryId = "eebda064-7412-4382-a11d-923503b240a1";
		
		public const string DefaultDiagramExtension = ".diagram";
		
		// Model explorer tool window identifier
		public const string ReportLanguageModelExplorerToolWindowId = "c1102562-567a-47a1-ae34-a1862089ee92";
	}
}
//
// Constants not generated from values in DesignerDefinition.dsl are defined below
//
namespace Company.ReportLanguage
{
	internal static partial class Constants
	{
		// Menu identifier
		public const string ReportLanguageCommandSetId = "0fbaaae5-57da-41e9-b299-a60119999dae";
	}
}